version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - ./data/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
