FROM node:18 AS base
WORKDIR /app
COPY package.json pnpm-lock.yaml /app/
COPY /apps/backend/package.json /app/apps/backend/package.json
RUN npm install -g pnpm
RUN pnpm install
COPY . /app
RUN pnpm --filter backend run build
CMD ["pnpm", "--filter", "backend", "run", "start"]
