// This file is auto-generated by pnpm run bootstrap.
// Do not edit this file manually.

export type User = {
  id: string;
  email: string;
  name: string;
  password: string;
  hashed_refresh_token: string | null;
  created_at: Date | null;
};

export type Categorie = {
  id: string;
  name: string;
  key: string;
  description: string | null;
  context: string | null;
};

export type Conversation = {
  id: string;
  user_id: string | null;
  category_id: string | null;
  title: string | null;
  created_at: Date | null;
};

export type Message = {
  id: string;
  conversation_id: string;
  user_id: string | null;
  category_id: string | null;
  role: string;
  content: string;
  created_at: Date | null;
};

